### ISSUE TITLE
[Ticket]: main is broken -- semantic merge conflict in UsageServiceSpendReader::new arity

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/lightbridge-authz#354]
### Type

Bug

### Summary

We need to fix a compile break on `main` because `origin/main` currently fails
`cargo check --workspace --all-targets --all-features` with E0061/E0063, blocking every developer
and CI job that builds this workspace.

Expected result:
> `origin/main` builds clean again under the exact CI commands (`cargo check`, `cargo fmt --
> --check`, `cargo clippy -- -D warnings`), with the two call sites that construct
> `UsageServiceSpendReader`/`UsageServiceClient` back in sync with the current 4-argument
> constructor and 4-field struct.

### Intent

Restore a buildable `main` as fast as possible. This is a pure mechanical fix — no behavior change
beyond making the newly-added `authz-budget` service wiring actually pass the CA bundle path it
was always supposed to pass (matching the pre-existing `authz-api` call site), so the intent is
purely "un-break the build," not a design change.

### Source of truth (links)

Diagnosis and fix scope handed down directly by the repo owner (Stephane Segning Lambou) in this
session's task brief, cross-referencing the two PRs whose combination caused the break:
#353 (`3d9d69c`, changed `UsageServiceSpendReader::new` to take a 4th `ca_bundle_path` argument)
and #351 (`7e99fd9`, added the `authz-budget` service wiring in
`crates/lightbridge-authz-rest/src/lib.rs` that still called the 3-argument form).

### Current Behavior

`cargo check --workspace --all-targets --all-features` on `origin/main` (`7e99fd9` merged after
`3d9d69c`) fails:

```
error[E0061]: this function takes 4 arguments but 3 arguments were supplied
  --> crates/lightbridge-authz-rest/src/lib.rs:2302:13
     argument #3 of type `std::option::Option<&str>` is missing
note: associated function defined here
  --> crates/lightbridge-authz-budget/src/spend.rs:224:12
```

A full run (rather than stopping at the first error) additionally surfaces two more instances of
the same collision in test code:

```
error[E0061]: this function takes 4 arguments but 3 arguments were supplied
   --> crates/lightbridge-authz-rest/tests/budget_rpc_it_tests.rs:159:13

error[E0063]: missing field `ca_bundle_path` in initializer of `UsageServiceClient`
   --> crates/lightbridge-authz-rest/tests/budget_rpc_it_tests.rs:901:37
```

This is a **semantic merge conflict**: PR #353 changed a function signature, PR #351 (merged
immediately after, in the same window) independently added a new call site against the
pre-#353 signature. Each PR was green in isolation because each was tested against a `main` that
lacked the other's change; git reported no textual conflict because the diffs don't overlap
line-for-line. Neither PR's own CI run could have caught this.

### Expected Behavior

- `crates/lightbridge-authz-rest/src/lib.rs`'s `start_budget_server` passes
  `usage_service.ca_bundle_path.as_deref()` as the 4th argument to `UsageServiceSpendReader::new`,
  identical in shape to the pre-existing `start_api_server` call site.
- `crates/lightbridge-authz-rest/tests/budget_rpc_it_tests.rs`'s equivalent call site and its
  `UsageServiceClient { .. }` struct literal are updated the same way.
- All three exact CI commands (`cargo check --workspace --all-targets --all-features`,
  `cargo fmt --all -- --check`, `cargo clippy --workspace --all-targets --all-features -- -D
  warnings`) pass with zero errors/warnings.

### Acceptance Criteria

- [ ] Given the 4-argument `UsageServiceSpendReader::new` signature from #353, when
      `start_budget_server` constructs one, then it passes the usage service's configured
      `ca_bundle_path` exactly like `start_api_server` already does.
- [ ] Given `origin/main`, when `cargo check --workspace --all-targets --all-features` is run
      exactly as CI runs it, then it completes with zero errors.
- [ ] Error cases are handled safely — the fix does not change the fail-closed
      `Spend::Unavailable` degrade behavior documented on `UsageServiceSpendReader`.
- [ ] Existing behavior is not broken — full `it-tests` suite for `lightbridge-authz-budget` and
      `lightbridge-authz-rest` passes with no regressions.
- [ ] Relevant tests are added/updated — the pre-existing CA-bundle and spend-reader test suites
      already cover this constructor; the fix brings the two call sites this ticket touches back
      into sync with those tests' expectations, and `budget_rpc_it_tests.rs`'s own suite (10
      tests) now compiles and passes again.
- [ ] Verification evidence is provided (see below); pending human sign-off.

### Out of Scope

- Any change to `UsageServiceSpendReader`'s CA-bundle verification behavior itself (that shipped
  correctly in #353; only the *new* call site from #351 was left behind).
- A process change to prevent future semantic merge conflicts (e.g. re-running CI on `main` after
  back-to-back merges touching related code) — worth raising separately, not bundled into this
  mechanical fix.

### Technical Context

- `crates/lightbridge-authz-budget/src/spend.rs:224` — `UsageServiceSpendReader::new` signature
  (4 args since #353).
- `crates/lightbridge-authz-rest/src/lib.rs` — two call sites: `start_api_server` (~line 1896,
  already correct) and `start_budget_server` (~line 2302, the one this ticket fixes).
- `crates/lightbridge-authz-rest/tests/budget_rpc_it_tests.rs` — a third call site (~line 159) and
  a `UsageServiceClient` struct literal (~line 902), both needing the same update.
- `crates/lightbridge-authz-core/src/config/mod.rs:430` — `UsageServiceClient` struct
  (`ca_bundle_path: Option<String>` field, added by #353).

### Risks

Low — this is a mechanical argument/field addition matching an already-established pattern at the
sibling call site. Verified via the full CI-equivalent command set plus real-database integration
tests for both affected crates (see Verification evidence).

### Test Plan

- `cargo check --workspace --all-targets --all-features`
- `cargo fmt --all -- --check`
- `cargo clippy --workspace --all-targets --all-features -- -D warnings`
- `cargo test -p lightbridge-authz-budget --features it-tests`
- `cargo test -p lightbridge-authz-rest --features it-tests`

### Verification evidence

Test output: all three CI-equivalent commands pass clean; `lightbridge-authz-budget` it-tests
(4+8+5+8+7+7+5+9 = 53 tests across 8 binaries) all green including the CA-bundle-specific suite
(`usage_service_ca_bundle_tests.rs`, 5/5); `lightbridge-authz-rest` it-tests all green including
the newly-fixed `budget_rpc_it_tests.rs` (10/10, previously would not even compile).

Manual verification steps: read both call sites and the `UsageServiceClient`/
`UsageServiceSpendReader::new` definitions directly rather than pattern-matching a guess; confirmed
the fix makes `start_budget_server` structurally identical to `start_api_server`'s existing,
already-correct wiring.

Logs / metrics checked: full `cargo check`/`clippy` output reviewed line by line for any other
E0061/E0063-shaped errors; none found beyond the three fixed here.

### Human accountable owner

@selast

### AI Usage Declaration

Understanding code, Proposing implementation, Generating code, Reviewing the diff

### Human verification completed

Filed autonomously by Claude Opus 5 (Claude Code) per the repo owner's task brief; boxes below are
intentionally left unticked pending the accountable owner's own review — see AI Usage Declaration.

- [ ] I understood the intent
- [ ] I checked the source of truth
- [ ] I reviewed all AI-generated text/code
- [ ] I verified the implementation manually
- [ ] I verified the tests
- [ ] I checked for hallucinated assumptions
- [ ] I documented remaining risks
- [ ] I am the accountable owner and accept responsibility for this ticket.
